### ISSUE TITLE
Provide a cell-level API

### ISSUE THREAD

**Issue by mootari** [mootari/observable-client#5]
TBD

**Comment by GordonSmith** [comment]
For my purposes I would like to see:
* `documentPull` => returns an array of cells (this exists today, but is blocked by an origin check)
* `documentPush(cells: Cell[])` => replaces the current array of cells with the supplied ones and bumps version etc.

**Comment by RandomFractals** [comment]
would be nice to also have a convenience method for updating single cell. something along the lines of:

```updateCell(notebookUrl, cellId, value, pinned)```

**Comment by mootari** [comment]
Please keep in mind that a document's node content is a list of changesets. To update a single cell, you'd:
1. determine the cell id by its name
2. create a changeset for that cell id and submit it

Updating a single cell by name seems a bit too high level and specific for a first iteration. However, ideally you should be able to implement these kinds of abstractions on top of the API.

**Comment by RandomFractals** [comment]
yeah, I agree. Maybe phase 2. I just thought it would make it really easy to have that as part of this api for notebook editors to just submit cell code changes and pinned state, which I suspect would be your most frequently used scenario for this api.
